-- Adds a public visit/click counter to the community_apps table, so
-- creators can see how much interest their app is getting and the
-- Applications section can offer a "Most Visited" sort.
--
-- Run this once in the Supabase SQL editor (Project -> SQL Editor -> New
-- query -> paste -> Run). It's safe to run even if you're not sure whether
-- part of it already ran — every statement below is written to be
-- re-runnable without erroring on a second run.
--
-- NOTE ON THE id COLUMN TYPE: this assumes community_apps.id is the
-- default Supabase "bigint generated by default as identity" primary key
-- (the standard default for a new table). If you set it up with a uuid
-- primary key instead, change every "bigint" below to "uuid" before
-- running this.

-- 1. New column: how many times "Visit" has been clicked for this app.
alter table public.community_apps
    add column if not exists visit_count bigint not null default 0;

-- 2. A public RPC that increments exactly one row by exactly one, and
-- nothing else — this is the ONLY way visit_count can change (no direct
-- table UPDATE grant to anon/authenticated), so it can safely be called by
-- anyone using the app, unauthenticated, without exposing arbitrary writes
-- to the table the way granting UPDATE directly would.
create or replace function public.increment_community_app_visit(p_app_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_count bigint;
begin
    update public.community_apps
    set visit_count = visit_count + 1
    where id = p_app_id
    returning visit_count into new_count;

    return new_count;
end;
$$;

-- 3. Let any client (including anonymous/unauthenticated ones — this app
-- doesn't require login to browse Applications) call the function above.
-- This does NOT grant them anything on the table itself, only permission
-- to invoke this one narrowly-scoped function.
grant execute on function public.increment_community_app_visit(bigint) to anon, authenticated;
