-- Riftgate: admin/super-admin "remove item for everyone" system
-- Run this once in the Supabase SQL Editor.
--
-- What this adds:
--   1. A new "removed_items" table listing every item an admin has removed
--      from Riftgate's catalog sections — read by every user so it can be
--      filtered out client-side, same pattern as mature_overrides.
--   2. An admin-gated RPC to remove an item, re-using your existing
--      verify_admin_login() the same way every other admin-only action in
--      the app already does.

-- 1. Removed items table -------------------------------------------------

create table if not exists public.removed_items (
    id bigint generated by default as identity primary key,
    section text not null,        -- 'game' | 'freegame' | 'movie' | 'show' | 'book' | 'manga' | 'comic'
    item_key text not null,       -- e.g. a RAWG id, a TMDB id, an Open Library work key
    item_name text,               -- for display in an admin list — not load-bearing
    removed_by text,               -- admin username who removed it
    created_at timestamptz not null default now(),
    unique (section, item_key)
);

-- Row Level Security: readable by anyone (every user's app needs this list
-- to filter what's shown), writable only through the admin-gated RPC below.
alter table public.removed_items enable row level security;

drop policy if exists "removed_items_select_all" on public.removed_items;
create policy "removed_items_select_all"
    on public.removed_items for select
    using (true);

-- 2. Admin-gated remove RPC -----------------------------------------------
-- Mirrors admin_toggle_item_mature: re-verifies the admin's own
-- username/password server-side via verify_admin_login before doing
-- anything. Idempotent — removing an already-removed item is a no-op,
-- not an error, so a double-click or two admins acting at once never fails.

create or replace function public.admin_remove_item(
    input_username text,
    input_password text,
    target_section text,
    target_item_key text,
    target_item_name text
) returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if not verify_admin_login(input_username, input_password) then
        raise exception 'Not authorized';
    end if;

    insert into public.removed_items (section, item_key, item_name, removed_by)
    values (target_section, target_item_key, target_item_name, input_username)
    on conflict (section, item_key) do nothing;

    return true;
end;
$$;
