-- Riftgate: age verification + mature-content system
-- Run this once in the Supabase SQL Editor.
--
-- What this adds:
--   1. date_of_birth + show_mature_content columns on the existing
--      "usernames" table (your account table).
--   2. A new "mature_overrides" table so an admin can manually force an
--      item to be treated as mature (or clear that), on top of the
--      app's own keyword-based detection.
--   3. An admin-gated RPC function to toggle an override, re-using your
--      existing verify_admin_login() the same way every other
--      admin-only action in the app already does.

-- 1. Account columns ---------------------------------------------------

alter table public.usernames
    add column if not exists date_of_birth date,
    add column if not exists show_mature_content boolean not null default false;

-- 2. Manual admin overrides ---------------------------------------------

create table if not exists public.mature_overrides (
    id bigint generated by default as identity primary key,
    section text not null,        -- 'book' | 'manga' | 'comic' | 'movie' | 'show'
    item_key text not null,       -- e.g. an Open Library work key, a TMDB id, a TVMaze show id
    item_name text,               -- for display in an admin list — not load-bearing
    marked_by text,                -- admin username who set this
    created_at timestamptz not null default now(),
    unique (section, item_key)
);

-- Row Level Security: readable by anyone (the app needs to check this
-- list client-side to filter what's shown), writable only through the
-- admin-gated RPC below (never directly).
alter table public.mature_overrides enable row level security;

drop policy if exists "mature_overrides_select_all" on public.mature_overrides;
create policy "mature_overrides_select_all"
    on public.mature_overrides for select
    using (true);

-- 3. Admin-gated toggle RPC ----------------------------------------------
-- Mirrors the existing admin RPC pattern: takes the admin's own
-- username/password, re-verifies them server-side via verify_admin_login,
-- and only then makes the change. Toggling means: if the item is
-- currently marked mature, this un-marks it; otherwise it marks it.
-- Returns true if the item is mature AFTER this call.

create or replace function public.admin_toggle_item_mature(
    input_username text,
    input_password text,
    target_section text,
    target_item_key text,
    target_item_name text
) returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    already_marked boolean;
begin
    if not verify_admin_login(input_username, input_password) then
        raise exception 'Not authorized';
    end if;

    select exists(
        select 1 from public.mature_overrides
        where section = target_section and item_key = target_item_key
    ) into already_marked;

    if already_marked then
        delete from public.mature_overrides
        where section = target_section and item_key = target_item_key;
        return false;
    else
        insert into public.mature_overrides (section, item_key, item_name, marked_by)
        values (target_section, target_item_key, target_item_name, input_username)
        on conflict (section, item_key) do nothing;
        return true;
    end if;
end;
$$;
