-- Adds download/open counters to The Vault's shared_files and shared_links
-- tables, so whoever posted a file or link can see how much use it's
-- getting.
--
-- Run this once in the Supabase SQL editor (Project -> SQL Editor -> New
-- query -> paste -> Run). Every statement below is safe to re-run.
--
-- NOTE ON id COLUMN TYPES: this assumes shared_files.id and shared_links.id
-- are the default Supabase "bigint generated by default as identity"
-- primary keys. If either table uses a uuid primary key instead, change
-- "bigint" to "uuid" in that table's function below before running.
--
-- NOTE ON get_shared_files / get_shared_links: these new columns will show
-- up automatically in the app IF those existing RPC functions return whole
-- rows (e.g. via SELECT * or RETURN QUERY SELECT sf.* ...). If they instead
-- list out specific columns, the new download_count/open_count fields
-- won't appear until that column list is also updated to include them —
-- easy to add if that turns out to be the case, just let Claude know.

-- 1. New counters, defaulting to 0 for every existing row.
alter table public.shared_files
    add column if not exists download_count bigint not null default 0;

alter table public.shared_links
    add column if not exists open_count bigint not null default 0;

-- 2. Public RPCs that each increment exactly one row by exactly one, and
-- nothing else — this is the ONLY way these counters can change (no direct
-- table UPDATE grant to anon/authenticated), so they're safe to call from
-- any client without exposing arbitrary writes to either table.
create or replace function public.increment_shared_file_download(p_file_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_count bigint;
begin
    update public.shared_files
    set download_count = download_count + 1
    where id = p_file_id
    returning download_count into new_count;

    return new_count;
end;
$$;

create or replace function public.increment_shared_link_open(p_link_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_count bigint;
begin
    update public.shared_links
    set open_count = open_count + 1
    where id = p_link_id
    returning open_count into new_count;

    return new_count;
end;
$$;

-- 3. Let any client call these two narrowly-scoped functions. This does
-- NOT grant anything on the tables themselves.
grant execute on function public.increment_shared_file_download(bigint) to anon, authenticated;
grant execute on function public.increment_shared_link_open(bigint) to anon, authenticated;
