-- =============================================================================
-- 0007 · vault_function
-- -----------------------------------------------------------------------------
-- Purpose
--   Bring The Vault back without any public storage rules. Since 0001 the
--   "riftgate-shares" bucket has no storage policies, so the publishable key
--   can't read, write or list it. All file transfers now go through the new
--   Edge Function `vault`, which checks the account password and then hands
--   out short-lived signed upload/download links using the service-role key.
--
--   * vault_record_upload(...)   records an upload only after checking the
--       password, that the object really exists in the bucket, and its real
--       size (≤ 50 MB). The storage path is generated by the Edge Function, so
--       nobody can point a Vault entry at someone else's object.
--   * force_clean_shared_folder(admin, pw)   the admin "clean now" action the
--       app already calls (it never existed in production).
--   * vault_orphan_paths()   objects in the bucket with no Vault entry (an
--       upload that never finished) older than 1 hour, so they can be removed.
--       Only names in the current format are listed (older leftovers can be
--       removed by hand in Storage).
--   * The functions that delete Vault rows (and so need matching storage
--       deletes) plus add_shared_file become service-role only, so rows and
--       stored files can't drift apart.
--   * Bucket stays private; a 50 MB per-file limit is set on it as well.
-- Prerequisites: 0002 (check_share_access / verify_admin_login rewrites), 0006.
-- Old-client effect (≤ 1.5.2): Vault upload/download already fails since 0001;
--   delete / clean-up of files now also fail there. Links are unaffected.
-- Verify:
--   select public.get_backend_info();   -- schema_version 7
--   select has_function_privilege('anon','public.vault_record_upload(text,text,text,text,text,integer)','execute'); -- false
--   select has_function_privilege('anon','public.delete_shared_file(text,bigint,text,text)','execute');            -- false
--   select public from storage.buckets where id = 'riftgate-shares';                                               -- false
-- Rollback: rollback_20260926000700.sql
-- =============================================================================
begin;

update storage.buckets
   set public = false,
       file_size_limit = 52428800
 where id = 'riftgate-shares';

create or replace function public.vault_record_upload(
  p_username text,
  p_password text,
  p_filename text,
  p_storage_path text,
  p_description text,
  p_expires_hours integer
)
returns public.shared_files
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_size bigint;
  v_row public.shared_files;
begin
  if not public.check_share_access(p_username, p_password) then
    raise exception 'Not authorized';
  end if;
  if p_expires_hours is null or p_expires_hours not in (1, 2, 4, 8, 12, 24) then
    raise exception 'Expiration must be 1, 2, 4, 8, 12, or 24 hours';
  end if;
  if p_storage_path is null
     or p_storage_path !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}-[A-Za-z0-9._-]{1,100}$' then
    raise exception 'Invalid storage path';
  end if;
  if p_filename is null or length(p_filename) = 0 or length(p_filename) > 255 then
    raise exception 'Invalid file name';
  end if;
  if p_description is not null and length(p_description) > 500 then
    raise exception 'Description is too long';
  end if;
  if exists (select 1 from public.shared_files where storage_path = p_storage_path) then
    raise exception 'That upload was already recorded';
  end if;

  select coalesce((o.metadata->>'size')::bigint, 0)
    into v_size
    from storage.objects o
   where o.bucket_id = 'riftgate-shares'
     and o.name = p_storage_path;
  if not found then
    raise exception 'Upload not found';
  end if;
  if v_size > 52428800 then
    raise exception 'File is larger than 50 MB';
  end if;

  insert into public.shared_files (filename, storage_path, file_size, description, uploader_username, expires_at)
  values (p_filename, p_storage_path, v_size, nullif(p_description, ''), p_username,
          now() + make_interval(hours => p_expires_hours))
  returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.force_clean_shared_folder(p_admin_username text, p_admin_password text)
returns setof public.shared_files
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if p_admin_password is null or not public.verify_admin_login(p_admin_username, p_admin_password) then
    raise exception 'Not authorized';
  end if;
  return query delete from public.shared_files returning *;
end;
$$;

create or replace function public.vault_orphan_paths()
returns setof text
language sql
stable
security definer
set search_path = public
as $$
  select o.name
    from storage.objects o
   where o.bucket_id = 'riftgate-shares'
     and o.created_at < now() - interval '1 hour'
     and o.name ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}-[A-Za-z0-9._-]{1,100}$'
     and not exists (select 1 from public.shared_files f where f.storage_path = o.name)
   order by o.created_at
   limit 100;
$$;

-- Service-role only: everything that creates or deletes Vault rows.
revoke execute on function public.vault_record_upload(text, text, text, text, text, integer) from public, anon, authenticated;
revoke execute on function public.force_clean_shared_folder(text, text) from public, anon, authenticated;
revoke execute on function public.vault_orphan_paths() from public, anon, authenticated;
revoke execute on function public.delete_shared_file(text, bigint, text, text) from public, anon, authenticated;
revoke execute on function public.cleanup_expired_shared_files(text, text) from public, anon, authenticated;
do $$
begin
  if to_regprocedure('public.add_shared_file(text,text,text,bigint,text,integer,text)') is not null then
    execute 'revoke execute on function public.add_shared_file(text,text,text,bigint,text,integer,text) from public, anon, authenticated';
  end if;
  if to_regprocedure('public.add_shared_file(text,text,text,bigint,text,text)') is not null then
    execute 'revoke execute on function public.add_shared_file(text,text,text,bigint,text,text) from public, anon, authenticated';
  end if;
end $$;
grant execute on function public.vault_record_upload(text, text, text, text, text, integer) to service_role;
grant execute on function public.force_clean_shared_folder(text, text) to service_role;
grant execute on function public.vault_orphan_paths() to service_role;
grant execute on function public.delete_shared_file(text, bigint, text, text) to service_role;
grant execute on function public.cleanup_expired_shared_files(text, text) to service_role;

create or replace function public.get_backend_info()
returns jsonb
language sql
stable
set search_path = public
as $$
  select jsonb_build_object('schema_version', 7, 'min_client_version', '1.5.2');
$$;

commit;
notify pgrst, 'reload schema';
